M48
; DRILL file {KiCad 9.0.7} date 2026-04-21T01:11:19-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-21T01:11:19-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.500
%
G90
G05
T1
X105.8Y-104.51
X105.8Y-110.29
T2
X108.8Y-94.4
T3
X52.35Y-85.6
X52.35Y-128.78
X95.35Y-128.78
M30
